### ISSUE TITLE
Bug: experimenter photo size

### ISSUE THREAD

**Issue by joshmoore** [ome/omero-web#172] opened 2020-05-06 09:14 UTC
```
2020-05-05 00:09:53,249 ERROR [ omeroweb.webclient.webclient_gateway] (proc.14980) getExperimenterPhotoSize():880 Traceback (most recent call last):
File "/opt/omero/web/venv3/lib64/python3.6/site-packages/omeroweb/webclient/webclient_gateway.py", line 878, in getExperimenterPhotoSize
im = Image.open(StringIO(photo))
TypeError: initial_value must be str or None, not bytes

```

Seen today on demo.

**Comment by will-moore** [comment] 2021-03-10 12:40
Duplicate of #255

**Closed by will-moore** 2021-03-10 12:40 UTC
