### ISSUE TITLE
Bug: ERROR logged for incorrect int of `$`

### ISSUE THREAD

**Issue by joshmoore** [ome/omero-web#222] opened 2020-09-18 14:12 UTC
```
2020-09-18 08:10:34,023 ERROR [ django.request] (proc.03241) handle_uncaught_exception():135 Internal Server Error: /webclient/render_image/3989228/$/
Traceback (most recent call last):
File "/opt/omero/web/venv3/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
response = get_response(request)
File "/opt/omero/web/venv3/lib64/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
response = self.process_exception_by_middleware(e, request)
File "/opt/omero/web/venv3/lib64/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/opt/omero/web/venv3/lib64/python3.6/site-packages/omeroweb/decorators.py", line 488, in wrapped
retval = f(request, *args, **kwargs)
File "/opt/omero/web/venv3/lib64/python3.6/site-packages/omeroweb/webgateway/views.py", line 1027, in render_image
jpeg_data = img.renderJpeg(z, t"," compression=compress_quality)
File "/opt/omero/web/venv3/lib64/python3.6/site-packages/omero/gateway/__init__.py", line 7890, in wrapped
return f(self, *args, **kwargs)
File "/opt/omero/web/venv3/lib64/python3.6/site-packages/omero/gateway/__init__.py", line 9333, in renderJpeg
self._pd.z = int(z)
ValueError: invalid literal for int() with base 10: '$'
```

**Comment by will-moore** [comment] 2021-03-10 12:26
This is a duplicate of #261

**Closed by will-moore** 2021-03-10 12:26 UTC

**Comment by joshmoore** [comment] 2021-03-10 15:38
(Sorry for the dupes. Thanks for tackling 'em!)
